<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="1"
            failures="0"
            tests="1">

  <testsuite name="cermati"
    errors="1" failures="0" hostname="" id="" package="cermati" skipped="0"
    tests="1" time="0.004000" timestamp="Mon, 14 Jan 2019 18:55:14 GMT">
  
    <testcase name="Housinganywhere " classname="cermati" time="0.004000" assertions="0">
    </testcase>
  

  
    <system-err>
        Error while running [Cermati / Housinganywhere ]:

  ReferenceError: max is not defined
    at Object.Housinganywhere  (/Users/guruprasathv/Documents/cermati/test/e2e/cermati.js:19:45)
    at Module.call (/Users/guruprasathv/Documents/cermati/node_modules/nightwatch/lib/runner/module.js:62:34)
    at /Users/guruprasathv/Documents/cermati/node_modules/nightwatch/lib/runner/testcase.js:70:29
    at _fulfilled (/Users/guruprasathv/Documents/cermati/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/guruprasathv/Documents/cermati/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/guruprasathv/Documents/cermati/node_modules/q/q.js:796:13)
    at /Users/guruprasathv/Documents/cermati/node_modules/q/q.js:556:49
    at runSingle (/Users/guruprasathv/Documents/cermati/node_modules/q/q.js:137:13)
    at flush (/Users/guruprasathv/Documents/cermati/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:112:11)
    </system-err>
  

  
  </testsuite>
</testsuites>
